### ISSUE TITLE
[bug] run `yarn core test` failed

### ISSUE THREAD

**Issue by Otto-J** [acapela/clientdb#9]
hi,I tried to run the repo and found some problems.

env:
node v16.13.1
yarn v3.2.1
macOS 12.2

step:
1. clone
2. install
3. run `yarn core test` 

expect:
no failed tests

actually:
has some failed test.

ps:
package.json has no `test` scripts

**Comment by pie6k** [comment]
Hey, thanks for reporting and sorry for late reply.

I just did check it, and it seems all the tests are passing:

<img width="906" alt="CleanShot 2022-07-27 at 09 35 45@2x" src="https://user-images.githubusercontent.com/7311462/181189142-104c6823-569f-4471-9730-6ed4b9b326bf.png">

Could you try again?

> package.json has no `test` scripts

This repository is monorepo. `yarn core` points to `core` package, and `core/package.json` has `test` script
